export const QUOTE_REQUESTED = 'QUOTE_REQUESTED';
export const QUOTE_RECEIVED = 'QUOTE_RECEIVED';
export const QUOTE_FAILED = 'QUOTE_FAILED';
export const QUOTE_FILM = 'QUOTE_FILM';
export const QUOTE_HOME = 'QUOTE_HOME';
export const QUOTE_TOOGLE_SEARCH = 'QUOTE_TOOGLE_SEARCH';
export const QUOTE_VALUE_SEARCH = 'QUOTE_VALUE_SEARCH';
